zstyle :plugin:fast-syntax-highlighting theme "voltage"
typeset -g FAST_THEME_NAME="voltage"
: ${FAST_HIGHLIGHT_STYLES[voltagedefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[voltageunknown-token]:=fg=#ff4d5e,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagereserved-word]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagealias]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagesuffix-alias]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagebuiltin]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagefunction]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagecommand]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltageprecommand]:=fg=#ff9a4d}
: ${FAST_HIGHLIGHT_STYLES[voltagecommandseparator]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagehashed-command]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagepath]:=fg=#5cc9f5}
: ${FAST_HIGHLIGHT_STYLES[voltagepath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[voltageglobbing]:=fg=#eb43f4,bold}
: ${FAST_HIGHLIGHT_STYLES[voltageglobbing-ext]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagehistory-expansion]:=fg=#5cc9f5,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagesingle-hyphen-option]:=fg=#17d5df}
: ${FAST_HIGHLIGHT_STYLES[voltagedouble-hyphen-option]:=fg=#17d5df}
: ${FAST_HIGHLIGHT_STYLES[voltageback-quoted-argument]:=fg=#ff9a4d}
: ${FAST_HIGHLIGHT_STYLES[voltagesingle-quoted-argument]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltagedouble-quoted-argument]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltagedollar-quoted-argument]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltageback-or-dollar-double-quoted-argument]:=fg=#17d5df}
: ${FAST_HIGHLIGHT_STYLES[voltageback-dollar-quoted-argument]:=fg=#17d5df}
: ${FAST_HIGHLIGHT_STYLES[voltageassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[voltageredirection]:=fg=#17d5df}
: ${FAST_HIGHLIGHT_STYLES[voltagecomment]:=fg=#6b6b6b}
: ${FAST_HIGHLIGHT_STYLES[voltagevariable]:=fg=#ff9a4d}
: ${FAST_HIGHLIGHT_STYLES[voltagemathvar]:=fg=#5cc9f5,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagemathnum]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagematherr]:=fg=#ff4d5e}
: ${FAST_HIGHLIGHT_STYLES[voltageassign-array-bracket]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagefor-loop-variable]:=fg=#ff9a4d}
: ${FAST_HIGHLIGHT_STYLES[voltagefor-loop-number]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagefor-loop-operator]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltagefor-loop-separator]:=fg=#fcf58d,bold}
: ${FAST_HIGHLIGHT_STYLES[voltageexec-descriptor]:=fg=#fcf58d,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagehere-string-tri]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltagehere-string-text]:=bg=#2a2427}
: ${FAST_HIGHLIGHT_STYLES[voltagehere-string-var]:=fg=#17d5df,bg=#2a2427}
: ${FAST_HIGHLIGHT_STYLES[voltagesecondary]:=free}
: ${FAST_HIGHLIGHT_STYLES[voltagecase-input]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagecase-parentheses]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltagecase-condition]:=bg=#2a2427}
: ${FAST_HIGHLIGHT_STYLES[voltagecorrect-subtle]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltageincorrect-subtle]:=fg=#ff4d5e}
: ${FAST_HIGHLIGHT_STYLES[voltagesubtle-separator]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagesubtle-bg]:=bg=#2a2427}
: ${FAST_HIGHLIGHT_STYLES[voltagepath-to-dir]:=fg=#5cc9f5,underline}
: ${FAST_HIGHLIGHT_STYLES[voltagepaired-bracket]:=bg=#2a2427}
: ${FAST_HIGHLIGHT_STYLES[voltagebracket-level-1]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagebracket-level-2]:=fg=#fcf58d,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagebracket-level-3]:=fg=#17d5df,bold}
: ${FAST_HIGHLIGHT_STYLES[voltageglobal-alias]:=fg=#b3e053,bold}
: ${FAST_HIGHLIGHT_STYLES[voltagesubcommand]:=fg=#ff9a4d}
: ${FAST_HIGHLIGHT_STYLES[voltagesingle-sq-bracket]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagedouble-sq-bracket]:=fg=#b3e053}
: ${FAST_HIGHLIGHT_STYLES[voltagedouble-paren]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltageoptarg-string]:=fg=#fcf58d}
: ${FAST_HIGHLIGHT_STYLES[voltageoptarg-number]:=fg=#eb43f4}
: ${FAST_HIGHLIGHT_STYLES[voltagerecursive-base]:=fg=#e7e7e7}
