#!/usr/bin/env bash

code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bradgashler.htmltagwrap
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dariofuzinato.vue-peek
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dunstontc.viml
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension eyhn.vscode-vibrancy
code --install-extension felixfbecker.php-intellisense
code --install-extension ffpetrovic.scss-scope-helper
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension foxundermoon.shell-format
code --install-extension kbgothamx.gothamx-code-snippets
code --install-extension kbgothamx.gothamx-theme
code --install-extension HookyQR.beautify
code --install-extension iceliu.highlight-icemode
code --install-extension idleberg.applescript
code --install-extension iocave.customize-ui
code --install-extension iocave.monkey-patch
code --install-extension junstyle.php-cs-fixer
code --install-extension kevinkyang.auto-comment-blocks
code --install-extension kube.theme-kay
code --install-extension lehni.vscode-fix-checksums
code --install-extension MarkThomasMiller.sorcerer
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-scss
code --install-extension naumovs.color-highlight
code --install-extension neilbrayfield.php-docblocker
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension pranaygp.vscode-css-peek
code --install-extension Rain.vue-scss-variable-scan
code --install-extension rifi2k.format-html-in-php
code --install-extension Shan.code-settings-sync
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension sleistner.vscode-fileutils
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension Zignd.html-css-class-completion
