# ~/.config/starship.toml
########################################
#prompt global settings
########################################

add_newline = false
command_timeout = 9000
format = "$all"

[character]
success_symbol = "[❯](#ffb86c)[❯](#bd93f9)[❯](#50fa7b)"
error_symbol = "[❯](#ff5555)[❯](#ff5555)[❯](#ff5555)"
vicmd_symbol = "[N](#bd93f9)"

[battery]
charging_symbol = "⚡️ "
disabled = false
discharging_symbol = "💀 "
full_symbol = "� "

[git_status]
disabled=true

[shell]
#zsh_indicator = "🦾 "
bash_indicator = "🐚 "
disabled = false
powershell_indicator = "_"

[[battery.display]] # red style when capacity is between 0% and 10%
style = "red"
threshold = 10

[[battery.display]] # yellow style when capacity is between 10% and 30%
style = "yellow"
threshold = 40

[hostname]
disabled = false
format = "@[$hostname]($style)"
ssh_only = true
style = "green"

[username]
disabled = false
format = " [$user]($style) "
show_always = true
style_root = "red"
style_user = "blue"

[php]
disabled = false
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
disabled = false
format = "[$symbol($version )]($style)"

[package]
disabled = false

[directory]
home_symbol = "~"
read_only = "🔒 "
style = "yellow"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = ""

[memory_usage]
disabled = true
format = "[${symbol}RAM: ${ram}]($style) "
style = "dimmed green"
threshold = -1

[jobs]
format = "[$symbol $number]($style) "
symbol = "🏃️ "
threshold = 4

[terraform]
disabled = true

[time]
disabled = true
format = "[$symbol][$time ]($style) "
style = "yellow"
symbol = "🕙 "
use_12hr = false
#time_format = "%Y/%m/%d %T"
time_range = "-" # always: time_range="00:00:00-23:59:59"

[custom.giturl]
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2>/dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=""
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=""
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=""
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=""
else
    GIT_REMOTE_SYMBOL=""
fi
echo "$GIT_REMOTE_SYMBOL "
"""
description = "Display symbol for remote Git server"
disabled = false
format = "$output "
shell = ["bash", "--noprofile", "--norc"]
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
