#!/usr/bin/env zsh
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
# No %F{...}/%f prompt escapes in any `format` value. zsh's native menu expands
# them, but fzf-tab does not: lib/-ftb-generate-header concatenates group names
# with raw ANSI and never calls `print -P`, so the escapes render literally
# ("%F{yellow}-- external command --%f") and their width breaks its column
# padding. Coloring group headers is fzf-tab's `group-colors` job instead.
zstyle ':completion:*:corrections' format '[%d (errors: %e)]'
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*:messages' format '[%d]'
zstyle ':completion:*:warnings' format '[no matches found]'
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion:*' format '[%d]'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec))'
zstyle ':completion:*' use-cache true
zstyle ':completion:*' rehash true

# Directories before plain files in file-completion lists (matches the
# --group-directories-first eza aliases and the fzf-tab previews).
zstyle ':completion:*' list-dirs-first true

# Let TAB expand an alias in place (offer its expansion as a candidate) before
# falling back to normal completion. e.g. `ll<TAB>` → `eza -la`.
zstyle ':completion:*' completer _expand_alias _complete _ignored
zstyle ':completion:*:expand-alias:*' group-name aliases

# fzf-tab captures the completion list itself, so zsh's own menu must be off.
zstyle ':completion:*' menu no

# NB: list-colors is NOT set here. $LS_COLORS is generated by vivid in .zshrc,
# *after* this file is sourced — so setting it here would only ever store an
# empty value, which .zshrc then immediately overwrites with the real one.

# disable sort when completing `git checkout`
# zstyle ':completion:*:git-checkout:*' sort false
# # set descriptions format to enable group support
# # NOTE: don't use escape sequences (like '%F{red}%d%f') here, fzf-tab will ignore them
# zstyle ':completion:*:descriptions' format '[%d]'
# # set list-colors to enable filename colorizing
# zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# # force zsh not to show completion menu, which allows fzf-tab to capture the unambiguous prefix
# zstyle ':completion:*' menu no
# # preview directory's content with eza when completing cd
# zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# # custom fzf flags
# # NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
# zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
# # To make fzf-tab follow FZF_DEFAULT_OPTS.
# # NOTE: This may lead to unexpected behavior since some flags break this plugin. See Aloxaf/fzf-tab#455.
# zstyle ':fzf-tab:*' use-fzf-default-opts yes
# # switch group using `<` and `>`
# zstyle ':fzf-tab:*' switch-group '<' '>'
