# Generated by fonts/build-tab-icons.py — do not edit.
#
# Command -> icon codepoint. The codepoints are plane-16 private use and
# only resolve under the Hack Nerd Font Color face that script also builds;
# each one is a Nerd Font glyph with an iTerm2 tint baked into the font's
# COLR table, because Ghostty gives the whole tab label a single color.
# Entries with no iTerm2 tint keep their plain Nerd Font codepoint.
#
# Written as a case rather than an associative array so it costs nothing at
# startup: the patterns compile into the .zwc and are only walked in preexec.
_tabtitle_glyph_for() {
  emulate -L zsh

  case $1 in
    zsh)                                                         _tabtitle_glyph=$'\U00100000' ;;  # shell, #C5DB00
    bash)                                                        _tabtitle_glyph=$'\U00100001' ;;  # shell, #FFFFFF
    fish)                                                        _tabtitle_glyph=$'\U00100002' ;;  # shell, #D8494F
    tcsh)                                                        _tabtitle_glyph=$'\U00100003' ;;  # shell, #00AEFF
    git|git-remote-ftp|git-remote-ftps|git-remote-http|git-remote-https)
                                                                 _tabtitle_glyph=$'\U00100004' ;;  # git, #FC6D26
    vim|vi|Vim)                                                  _tabtitle_glyph=$'\U00100005' ;;  # vim, #008F00 (iTerm2 #007F00, lifted)
    nvim)                                                        _tabtitle_glyph=$'\U00100006' ;;  # vim, #54A23D
    nano|pico)                                                   _tabtitle_glyph=$'\U0000F044' ;;  # nano/code, no iTerm2 tint
    emacs|Emacs)                                                 _tabtitle_glyph=$'\U00100007' ;;  # emacs, #896BBD (iTerm2 #7E5CB7, lifted)
    tail|less|more)                                              _tabtitle_glyph=$'\U0000F02D' ;;  # read, no iTerm2 tint
    grep|egrep|fgrep|search|find|lookup)                         _tabtitle_glyph=$'\U00100008' ;;  # search, #9CCC65
    top|htop|iftop)                                              _tabtitle_glyph=$'\U0000F0E4' ;;  # monitor, no iTerm2 tint
    ping)                                                        _tabtitle_glyph=$'\U00100009' ;;  # bullhorn, #00AEFF
    curl)                                                        _tabtitle_glyph=$'\U0010000A' ;;  # curl, #9CCC65
    wget|http)                                                   _tabtitle_glyph=$'\U0000F0AC' ;;  # http, no iTerm2 tint
    docker|docker-compose)                                       _tabtitle_glyph=$'\U0010000B' ;;  # docker, #0EB7ED
    make|gmake)                                                  _tabtitle_glyph=$'\U0010000C' ;;  # compile, #00AEFF
    cc|ccache|clang|gcc|xcodebuild)                              _tabtitle_glyph=$'\U0000F085' ;;  # compile, no iTerm2 tint
    zip|unzip|gzip|gunzip|gzcat|bzip2|bunzip2|tar|gz|winzip|zar) _tabtitle_glyph=$'\U0010000D' ;;  # zip, #FD9126
    node)                                                        _tabtitle_glyph=$'\U0010000E' ;;  # nodejs, #7EBF00
    npm|npx)                                                     _tabtitle_glyph=$'\U0010000F' ;;  # npm, #DE3F44 (iTerm2 #C12127, lifted)
    yarn|yarnpkg)                                                _tabtitle_glyph=$'\U00100010' ;;  # yarn, #2C8EBB
    php|composer|composer.phar)                                  _tabtitle_glyph=$'\U0000E73D' ;;  # php, no iTerm2 tint
    python|python[0-9.]*|Python|ipython|IPython|apython|pip|easy_install)
                                                                 _tabtitle_glyph=$'\U00100011' ;;  # python, #FFDF59
    ruby|irb|rake|sidekiq)                                       _tabtitle_glyph=$'\U00100012' ;;  # ruby, #D64943 (iTerm2 #CC342D, lifted)
    perl)                                                        _tabtitle_glyph=$'\U0000E769' ;;  # perl, no iTerm2 tint
    java|javac)                                                  _tabtitle_glyph=$'\U0000E738' ;;  # java, no iTerm2 tint
    go)                                                          _tabtitle_glyph=$'\U0000E627' ;;  # go, no iTerm2 tint
    lein|planck|lumo)                                            _tabtitle_glyph=$'\U0000E768' ;;  # clojure, no iTerm2 tint
    elixir|elixirc|iex|mix)                                      _tabtitle_glyph=$'\U00100013' ;;  # elixir, #AF49E4 (iTerm2 #440E60, lifted)
    beam|beam.smp|dialyzer|epmd|erl|erlc|escript|run_erl|to_erl) _tabtitle_glyph=$'\U00100014' ;;  # erlang, #DB3E64 (iTerm2 #7F1831, lifted)
    ethereum|testrpc)                                            _tabtitle_glyph=$'\U00100015' ;;  # ethereum, #8A93B1
    geth)                                                        _tabtitle_glyph=$'\U00100016' ;;  # ethereum, #B2FF59
    heroku)                                                      _tabtitle_glyph=$'\U00100017' ;;  # heroku, #7874B0 (iTerm2 #6762A6, lifted)
    postgres|psql)                                               _tabtitle_glyph=$'\U00100018' ;;  # postgres, #3B7DC0 (iTerm2 #27527E, lifted)
    mongo|mongod|mongodb)                                        _tabtitle_glyph=$'\U00100019' ;;  # database, #589636
    mysql|sqlite3|postmaster|pgbench|pg_dump|pg_dumpall|pg_restore|pg_upgrade|redis-cli|redis-server|redis-sentinel|redis-benchmark|redis-check-aof|redis-check-rdb)
                                                                 _tabtitle_glyph=$'\U0000F1C0' ;;  # database, no iTerm2 tint
    claude)                                                      _tabtitle_glyph=$'\U0010001A' ;;  # claude_code, #CC7C5E
    *)                                                           _tabtitle_glyph=$'\U0010001B' ;;  # shell, #00AEFF
  esac
}
