#! /usr/bin/env sh

npm=(
  @vue/cli
  eslint
  prettier
  @prettier/plugin-php
  eslint-plugin-prettier
  eslint-config-prettier
  eslint-plugin-vue
  eslint-config-standard
  eslint-plugin-import
  eslint-plugin-promise
  eslint-plugin-node
  babel-eslint
  generator-code
  yo
  fast-cli
  fkill-cli
  vtop
  vsce
  @vue/eslint-config-prettier
  @vue/cli-service-global
  cli-error-notifier
  electron
  npm-check
  stylelint
  stylelint-config-standard
  alfred-npms
  electerm
  firebase-tools
  ntl
  prettier-init
  readme-md-generator
  npx
  auto-changelog
)
